-- MySQL Script generated by MySQL Workbench
-- Fri Aug 31 17:40:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AlmacenBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AlmacenBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AlmacenBD` DEFAULT CHARACTER SET utf8 ;
USE `AlmacenBD` ;

-- -----------------------------------------------------
-- Table `AlmacenBD`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`Empresa` (
  `idEmpresa` INT NOT NULL,
  `NomEmpresa` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmacenBD`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`Trabajador` (
  `idTrabajador` INT NOT NULL,
  `Nombre` VARCHAR(50) NULL,
  `Apellidos` VARCHAR(100) NULL,
  `Dni` VARCHAR(8) NULL,
  `Direcc` VARCHAR(60) NULL,
  `idEmpresa` INT NOT NULL,
  `telefono` VARCHAR(11) NULL,
  `estado` BIT NOT NULL,
  PRIMARY KEY (`idTrabajador`),
  INDEX `fk_Trabajador_Empresa1_idx` (`idEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Trabajador_Empresa1`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `AlmacenBD`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmacenBD`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `pass` VARCHAR(350) NULL,
  `idTrabajador` INT NOT NULL,
  `estado` BIT NOT NULL,
  `nivel` BIT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Trabajador1_idx` (`idTrabajador` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Trabajador1`
    FOREIGN KEY (`idTrabajador`)
    REFERENCES `AlmacenBD`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmacenBD`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`Pedido` (
  `idPedido` INT NOT NULL,
  `nroPedido` VARCHAR(7) NOT NULL,
  `total` DECIMAL(10,2) NULL,
  `fecha` DATE NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `validado` BIT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `AlmacenBD`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmacenBD`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`Marca` (
  `idMarca` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `estado` BIT NOT NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmacenBD`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `NomCategoria` VARCHAR(50) NOT NULL,
  `estado` BIT NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmacenBD`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`Producto` (
  `idProducto` INT NOT NULL,
  `descrip` VARCHAR(80) NOT NULL,
  `nroSerie` VARCHAR(20) NULL,
  `stock` DECIMAL(10,2) NOT NULL,
  `unidMed` VARCHAR(10) NULL,
  `modelo` VARCHAR(50) NULL,
  `precio` DECIMAL(10,2) NULL,
  `estado` BIT NULL,
  `ubicacion` VARCHAR(45) NULL,
  `foto` VARCHAR(400) NULL,
  `idMarca` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Marca1_idx` (`idMarca` ASC) VISIBLE,
  INDEX `fk_Producto_Categoria1_idx` (`idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Marca1`
    FOREIGN KEY (`idMarca`)
    REFERENCES `AlmacenBD`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `AlmacenBD`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmacenBD`.`Detalle_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`Detalle_Pedido` (
  `idPedido` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `Precio` DECIMAL(10,2) NOT NULL,
  `Cantidad` DECIMAL(10,2) NULL,
  `SubTotal` DECIMAL(10,2) NULL,
  PRIMARY KEY (`idPedido`, `idProducto`),
  INDEX `fk_Detalle_Pedido_Pedido_idx` (`idPedido` ASC) VISIBLE,
  INDEX `fk_Detalle_Pedido_Producto1_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Detalle_Pedido_Pedido`
    FOREIGN KEY (`idPedido`)
    REFERENCES `AlmacenBD`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Pedido_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `AlmacenBD`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmacenBD`.`Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`Almacen` (
  `idAlmacen` INT NOT NULL,
  `nomAlmacen` VARCHAR(50) NULL,
  PRIMARY KEY (`idAlmacen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmacenBD`.`Proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`Proveedor` (
  `idProveedor` INT NOT NULL,
  `nomProv` VARCHAR(100) NOT NULL,
  `ruc` VARCHAR(11) NOT NULL,
  `direcc` VARCHAR(100) NULL,
  `telef` VARCHAR(23) NULL,
  `correo` VARCHAR(50) NULL,
  `estado` BIT NOT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmacenBD`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`Compra` (
  `idCompra` INT NOT NULL,
  `idProveedor` INT NOT NULL,
  `subTotal` DECIMAL(10,2) NOT NULL,
  `igv` DECIMAL(10,2) NOT NULL,
  `dcto` DECIMAL(10,2) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `nroComprob` VARCHAR(15) NOT NULL,
  `fechaCompra` DATE NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_Compra_Proveedor1_idx` (`idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Proveedor1`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `AlmacenBD`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmacenBD`.`Producto_Almacen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`Producto_Almacen` (
  `idProducto` INT NOT NULL,
  `idAlmacen` INT NOT NULL,
  `Cant` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idCompra` INT NULL,
  INDEX `fk_Producto_Almacen_Producto1_idx` (`idProducto` ASC) VISIBLE,
  PRIMARY KEY (`idProducto`, `idAlmacen`),
  INDEX `fk_Producto_Almacen_Almacen1_idx` (`idAlmacen` ASC) VISIBLE,
  INDEX `fk_Producto_Almacen_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Producto_Almacen_Compra1_idx` (`idCompra` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Almacen_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `AlmacenBD`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Almacen_Almacen1`
    FOREIGN KEY (`idAlmacen`)
    REFERENCES `AlmacenBD`.`Almacen` (`idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Almacen_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `AlmacenBD`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Almacen_Compra1`
    FOREIGN KEY (`idCompra`)
    REFERENCES `AlmacenBD`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmacenBD`.`MovProd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`MovProd` (
  `idMovProd` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `idAlmacen` INT NOT NULL,
  `cant` DECIMAL(10,2) NOT NULL,
  `tipoMov` BIT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `stock` DECIMAL(10,2) NOT NULL,
  `idTrabajador` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `unidad` VARCHAR(45) NULL,
  `estado` BIT NULL,
  `idProveedor` INT NOT NULL,
  PRIMARY KEY (`idMovProd`),
  INDEX `fk_MovProd_Producto_Almacen1_idx` (`idProducto` ASC, `idAlmacen` ASC) VISIBLE,
  INDEX `fk_MovProd_Trabajador1_idx` (`idTrabajador` ASC) VISIBLE,
  INDEX `fk_MovProd_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_MovProd_Proveedor1_idx` (`idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_MovProd_Producto_Almacen1`
    FOREIGN KEY (`idProducto` , `idAlmacen`)
    REFERENCES `AlmacenBD`.`Producto_Almacen` (`idProducto` , `idAlmacen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MovProd_Trabajador1`
    FOREIGN KEY (`idTrabajador`)
    REFERENCES `AlmacenBD`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MovProd_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `AlmacenBD`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MovProd_Proveedor1`
    FOREIGN KEY (`idProveedor`)
    REFERENCES `AlmacenBD`.`Proveedor` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlmacenBD`.`Detalle_Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlmacenBD`.`Detalle_Compra` (
  `idCompra` INT NOT NULL,
  `idProducto` INT NOT NULL,
  `cantidad` DECIMAL(10,2) NOT NULL,
  `precUnit` DECIMAL(10,2) NOT NULL,
  `Total` DECIMAL(10,2) NOT NULL,
  INDEX `fk_Detalle_Compra_Compra1_idx` (`idCompra` ASC) VISIBLE,
  INDEX `fk_Detalle_Compra_Producto1_idx` (`idProducto` ASC) VISIBLE,
  PRIMARY KEY (`idCompra`, `idProducto`),
  CONSTRAINT `fk_Detalle_Compra_Compra1`
    FOREIGN KEY (`idCompra`)
    REFERENCES `AlmacenBD`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Compra_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `AlmacenBD`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
